services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Badri@8344
      MYSQL_DATABASE: lldb
      MYSQL_USER: root
      MYSQL_PASSWORD: Badri@8344
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ../cicd-project-backend
    container_name: backend_app
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/lldb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Badri@8344
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8081"

  frontend:
    build: ../cicd-project-frontend
    container_name: frontend_app
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db_data:
