version: "3.8"
services:
  backend:
    build:
      context: ./cicd-project-backend
      dockerfile: Dockerfile.backend
    container_name: backend-service
    ports:
      - "8081:8081"

  frontend:
    build:
      context: ./cicd-project-frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend-service
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8081
    depends_on:
      - backend
