version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: db-service
    environment:
      MYSQL_ROOT_PASSWORD: Badri@8344
      MYSQL_DATABASE: lldb
      MYSQL_USER: root
      MYSQL_PASSWORD: Badri@8344
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: ../cicd-project-backend
      dockerfile: Dockerfile
    container_name: backend-service
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/lldb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Badri@8344
    ports:
      - "2004:2004"
    networks:
      - app-network

  frontend:
    build:
      context: ../cicd-project-frontend
      dockerfile: Dockerfile
    container_name: frontend-service
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
